###
GET http://localhost:8080/collect/list
###
POST http://localhost:8080/collect/save
Content-Type: application/json

{
  "studentId": 2,
  "positionId": 123452
}

###
###
POST http://localhost:8080/collect/delete/
Content-Type: application/json

{
  "studentId": 735,
  "positionId": 1661
}
###


DELETE http://localhost:8080/collect/delete/batch?ids=24,25,26

###


POST http://localhost:8080/collect/selfcollect
Content-Type: application/json

{
  "studentId": 2
}

###