###
GET http://localhost:8080/position/list?createtime=2013-05-09
###
POST http://localhost:8080/position/save
Content-Type: application/json

{
  "name": "JAVA开发",
  "employId": 1,
  "industryId": 4,
  "type": "求职类型",
  "experience": "2-3年",
  "salary": "2K-3K",
  "education": "大专以上",
  "tags": "java,C,PHP",
  "status": "1",
  "createtime": "2017-05-06",
  "updatetime": "2008-09-06",
  "content": "职位状态"
}

###
###
DELETE http://localhost:8080/position/delete/21

###



DELETE http://localhost:8080/position/delete/batch?ids=24,25,26

###