###
GET http://localhost:8080/sorts/list

###
POST http://localhost:8080/sorts/save
Content-Type: application/json

{

  "sortName": "Edith 22",
  "sortAlias": "rgBCDqmKtI",
  "parentSortId": "5288",
  "sortDescription": "Such sessions are"
}

###
###
GET http://localhost:8080/sorts/delete/1

###