

###
POST http://localhost:8080/sysjob/add
Content-Type: application/json

{
  "id": 3,
  "name": "测试定时任务",
  "className": "com.example.xblog.job.TaskJob",
  "cronExpression": "0/4 * * * * ?",
  "param": "{userid:1}",
  "status": false,
  "remark": "2",
  "createBy": 0,
  "sort": 0
}
###

###
POST http://localhost:8080/sysjob/update
Content-Type: application/json

{
  "id": 3,
  "name": "1测试定时任务2221",
  "className": "com.example.xblog.job.TaskJob",
  "cronExpression": "0/2 * * * * ?",
  "param": 1234,
  "status": false
}
###
###
GET http://localhost:8080/sysjob/delete/3
###

###
POST http://localhost:8080/sysjob/comment
Content-Type: application/json

{
  "id": 3,
  "name": "测试定时任务2222222",
  "className": "com.example.xblog.job.TaskJob",
  "cronExpression": "0/2 * * * * ?",
  "param": 555555555555555,
  "status": true
}
###