

###
POST http://localhost:8080/webmessage/sendall
Content-Type: application/json

{
  "type": "1",
  "comment": "登陆成功",
  "userid": "1"
}

###

###
POST http://localhost:8080/webmessage/send
Content-Type: application/json

{
  "type": "3",
  "comment": "44443333",
  "userid": "1"
}

###
###
POST http://localhost:8080/webmessage/collect
Content-Type: application/json

{
  "type": "2",
  "comment": "4444",
  "userid": "userid2"
}

###
